install:
	cd account-service && bun install &&
	cd auth-service && bun install &&
	cd card-service && bun install &&
	cd manager-service && bun install &&
	cd notification-service && bun install &&
	cd user-service && bun install